#!/bin/bash

# This script populates the directory ABOVE the repository root with the
# deployed software and the output directory.
#
# Suppose the filesystem looked like this:
# aws-object-search
# └── repo
#
# After running "./repo/deploy SUFFIX", the filesystem would look like this.
# aws-object-search
# ├── aws-object-search-SUFFIX
# ├── micromamba
# ├── repo
# └── s3_objects
#
# The default SUFFIX is "dev".

set -euo pipefail
# set -x

main() {
    THIS_SCRIPT="${BASH_SOURCE[0]}"
    SUFFIX="${1:-dev}"

    # Resolve the absolute path to the directory containing the script
    REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    if [[ -z "${__SANITIZED_ENV:+x}" ]]; then
        # If not already in a sanitized environment, run the script in a sanitized environment
        echo "Sanitizing environment"
        exec "$REPO_DIR"/scripts/sanitize-command "$THIS_SCRIPT" "$@"
    else
        # If already in a sanitized environment, just run the script
        echo "Running in a sanitized environment:"
        cd  # $HOME
        deploy "$SUFFIX"
    fi
}

# Define deploy function with argument
deploy() {
    local SUFFIX="$1"
    echo "Running deploy() in $(pwd) with SUFFIX=$SUFFIX"
    env
    echo
    # Phase 1: Get micromamba.
    bash repo/scripts/fetch-micromamba.sh
    # Phase 2: Create deployment environment.
    ./micromamba create -y -p ./aws-object-search-$SUFFIX python=3.13 uv
    # Phase 3: Populate deployment environment with applicatien.
    export PATH=$PWD/aws-object-search-dev/bin:$PATH
    if [[ $SUFFIX == "dev" ]]; then
        EDITABLE="-e"
    else
        EDITABLE=""
    fi
    uv pip install --system $EDITABLE repo
    # Phase 4: create output directory.
    mkdir -p s3_objects
}

main "$@"
